# final prection
1. load text csv
2. load prepeocess text data
3. load model
4. make prediction
5. convert prediction to csv with header sentiment_prediction
6. merge csv prediction with text csv
7. save predcition

In [1]:
# import libraries
import joblib
import numpy as np
import pandas as pd

In [2]:
#load text cvs, processed test and model
test_df = pd.read_csv(r"C:\Users\GIGABYTE\Desktop\drug-sentiment-analysis\data\processed\test_data.csv")
X_test = joblib.load(r"C:\Users\GIGABYTE\Desktop\drug-sentiment-analysis\data\processed\X_test.pkl")
model = joblib.load(r"C:\Users\GIGABYTE\Desktop\drug-sentiment-analysis\model\best_rf.joblib")

In [ ]:
#making prediction
predictions = model.predict(X_test)

In [4]:
# convert predicgtions csv
submission_df = pd.DataFrame({
    "unique_hash" : test_df["unique_hash"],
    "predicted_sentiment" : predictions
})

In [5]:
submission_df.head()

                                unique_hash  predicted_sentiment
0  9e9a8166b84114aca147bf409f6f956635034c08                    2
1  e747e6822c867571afe7b907b51f0f2ca67b0e1a                    2
2  50b6d851bcff4f35afe354937949e9948975adf7                    2
3  7f82ec2176ae6ab0b5d20b5ffc767ac829f384ae                    2
4  8b37d169dee5bdae27060949242fb54feb6a7f7f                    2

In [6]:
#concatinate submission_df and test_df on unique_hash
final_df = pd.merge(test_df, submission_df, on="unique_hash", how="left")
final_df.head()

,unique_hash,text,drug,cleaned_text,clean_drug,predicted_sentiment
0,9e9a8166b84114aca147bf409f6f956635034c08,"256 (previously stable on natalizumab), with 5...",fingolimod,previously stable natalizumab switching fingol...,fingolimod,2
1,e747e6822c867571afe7b907b51f0f2ca67b0e1a,On fingolimod and have been since December 201...,fingolimod,fingolimod since december way describe better ...,fingolimod,2
2,50b6d851bcff4f35afe354937949e9948975adf7,Apparently it's shingles! :-/ I do have a few ...,humira,apparently shingle red spot left breast appear...,humira,2
3,7f82ec2176ae6ab0b5d20b5ffc767ac829f384ae,If the Docetaxel doing once a week x3 weeks th...,tagrisso,docetaxel week x week week claim less harsh ef...,tagrisso,2
4,8b37d169dee5bdae27060949242fb54feb6a7f7f,"CC, Stelara worked in a matter of days for me....",stelara,cc stelara worked matter day gi willing jump h...,stelara,2

In [10]:
final_df[final_df["predicted_sentiment"] == 1].head()

,unique_hash,cleaned_text,clean_drug,predicted_sentiment
17,245536722a649761b30a740031040a937d8b3e0e,hello guy hope well didnt know post topic excu...,gilenya,1
21,4c8c81babeb983eb8b420a0f6d49b7eb0e230c8b,thanks clo dunno much longer go like ive excru...,entyvio,1
49,a897b32296fbaef1a724f68c994dddd23d7bee9e,thankyou much md antijcv treatment market many...,gilenya,1
60,5223cdaa8d259f7232db72bd5b91a708567ed855,second go round avonex long story first time a...,gilenya,1
68,eeed9a8e13ac71f4bf74f727ee1944bfc6b59411,waynexxl glad fine coming gilenya one drug rea...,gilenya,1

In [9]:
final_df = final_df[["unique_hash", "cleaned_text", "clean_drug", "predicted_sentiment"]]

In [11]:
#save final_df to csv and submission_df to csv
final_df.to_csv(r"C:\Users\GIGABYTE\Desktop\drug-sentiment-analysis\predictions\final_predictions.csv", index=False)

submission_df.to_csv(r"C:\Users\GIGABYTE\Desktop\drug-sentiment-analysis\predictions\submission_predictions.csv", index=False)